# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49a44d3418ae2be37682d653d19b6bd3f72f19768a9a438103ee88fe59fb4b3aa817d0aca62943f97126a78c71cd357b922e496d4b731897c4a6b3faed238f26

test:
  secret_key_base: c3417cfd8f4a01144f84be68776ef025c34cc7c14e39eff1ad703e6fd0079ce503f2c4c414822e54a8845efe7f9a9ee3bbba00f04f2d1857c3f1dae38d72b771

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
